### ISSUE TITLE
for dp2.0 ,how to call the dp_c_api by fortran 

### ISSUE THREAD

**Issue by luowh35** [robinzyb/DeePMD-kit-Fortran-Cpp-interface#8]
I want to evaluate the energy using fortran ,but there is no straight fortran code now, could you update the code for C/Fortran part?thanks!!

**Comment by robinzyb** [comment]
https://github.com/robinzyb/DeePMD-kit-Fortran-Cpp-interface/blob/master/deepmd_wrapper.f90
You can import the function `compute_nnp` in this module

**Comment by luowh35** [comment]
now dp2.0 don't have this

**Comment by luowh35** [comment]
now dp2.0's c_api doesn't have the function compute_nnp ,see https://github.com/deepmodeling/deepmd-kit/blob/master/source/api_c/include/c_api.h,it change the new function, using the DP_DeepPotCompute:
extern void DP_DeepPotCompute(DP_DeepPot* dp,
                              const int natom,
                              const double* coord,
                              const int* atype,
                              const double* cell,
                              double* energy,
                              double* force,
                              double* virial,
                              double* atomic_energy,
                              double* atomic_virial);

**Comment by luowh35** [comment]
sorry i don't know how to operate the github...

**Comment by robinzyb** [comment]
Sorry I didn't work on this plugin now. It would take time to test the modified code. but it is simple to modify this file to get the code work. 
the `comput_nnp` is defined by myself in [c_wrapper.h](https://github.com/robinzyb/DeePMD-kit-Fortran-Cpp-interface/blob/master/c_wrapper.h). Now you can use the function `DP_DeepPotCompute` 
in https://github.com/deepmodeling/deepmd-kit/blob/master/source/api_c/include/c_api.h.


and modify the `CALL compute_nnp_c` in `deepmd_wrapper.f09` to `CALL DP_DeepPotCompute` accordingly.

**Comment by luowh35** [comment]
I totally agree with what you said, but my programming experience is limited, so I want to ask a few questions
1. Can fortran directly call the functions in c_api.h, such as `DP_DeepPotCompute` ?
2. if can, how to compile the fortran program such as `deepmd_wrapper.f90`? like gfortran deepmd_wrapper.f90

**Comment by robinzyb** [comment]
Sorry, I don't understand what you are trying to convey. You can use gfortran to compile it. The deepmd use CMAKE to create a makefile which is just a recipe to automatically execute commands like `gfortran xxx.f90`, `gcc xxx.cpp`

**Comment by luowh35** [comment]
Sorry, I didn't express clearly. What I want to ask is that now deepmd-kit provides `c_api.h`. I want to know whether fortran can directly call the functions in `c_api.h` through `iso_c_binding`. If not, what should be the correct calling method.

**Comment by luowh35** [comment]
should I write a `xx.c` program to define the function such as `DP_DeepPotCompute`, then I use the fortran to call the c function?

**Comment by robinzyb** [comment]
> Sorry, I didn't express clearly. What I want to ask is that now deepmd-kit provides `c_api.h`. I want to know whether fortran can directly call the functions in `c_api.h` through `iso_c_binding`. If not, what should be the correct calling method.

It can be called if you link `c_api.o` using compiler, which is compiled from  a `c_api.cc` https://github.com/deepmodeling/deepmd-kit/blob/master/source/api_c/src/c_api.cc

**Comment by luowh35** [comment]
Thank you so much, I check my `dp_root/include`, and only see the head file `c_api.h`.
But in the `c_api.cc`, It should link the `#include "DataModifier.h"`,`#include "DeepPot.h"`,`#include "DeepTensor.h"`,`#include "c_api_internal.h"`,`#include "common.h"`,how can I get these head file?

**Comment by luowh35** [comment]
I change the function name in `deepmd_wrapper.f90` and `fortran_call.f90`, at the same time ,I change the `c_wrapper.cpp` to `c_api.cc`,and I successfully compile the `c_api.cc`,`fortran_call.f90`and`deepmd_wrapper.f90` to their `xx.o` file, but when I link them together, error occured:
`c_api.o：在函数‘DP_DeepPot::DP_DeepPot()’中：
c_api.cc:(.text+0x1f4)：对‘deepmd::DeepPot::DeepPot()’未定义的引用
c_api.o：在函数‘DP_NewDeepPot’中：
c_api.cc:(.text+0x30f)：对‘deepmd::DeepPot::DeepPot(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
c_api.cc:(.text+0x360)：对‘deepmd::DeepPot::~DeepPot()’未定义的引用
c_api.cc:(.text+0x3f2)：对‘deepmd::DeepPot::~DeepPot()’未定义的引用
c_api.o：在函数‘DP_NewDeepPotWithParam’中：
c_api.cc:(.text+0x647)：对‘deepmd::DeepPot::DeepPot(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
c_api.cc:(.text+0x67d)：对‘deepmd::DeepPot::~DeepPot()’未定义的引用
c_api.cc:(.text+0x73d)：对‘deepmd::DeepPot::~DeepPot()’未定义的引用
c_api.o：在函数‘DP_NewDeepPotWithParam2’中：
c_api.cc:(.text+0x925)：对‘deepmd::DeepPot::DeepPot(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
c_api.cc:(.text+0x95b)：对‘deepmd::DeepPot::~DeepPot()’未定义的引用
c_api.cc:(.text+0x9dc)：对‘deepmd::DeepPot::~DeepPot()’未定义的引用
c_api.o：在函数‘DP_DeepPotModelDevi::DP_DeepPotModelDevi()’中：
c_api.cc:(.text+0xb0e)：对‘deepmd::DeepPotModelDevi::DeepPotModelDevi()’未定义的引用
c_api.o：在函数‘DP_NewDeepPotModelDevi’中：
c_api.cc:(.text+0xc4a)：对‘deepmd::DeepPotModelDevi::DeepPotModelDevi(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)’未定义的引用
c_api.cc:(.text+0xc8c)：对‘deepmd::DeepPotModelDevi::~DeepPotModelDevi()’未定义的引用
c_api.cc:(.text+0xd07)：对‘deepmd::DeepPotModelDevi::~DeepPotModelDevi()’未定义的引用
c_api.o：在函数‘DP_NewDeepPotModelDeviWithParam’中：
c_api.cc:(.text+0xfbc)：对‘deepmd::DeepPotModelDevi::DeepPotModelDevi(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)’未定义的引用
c_api.cc:(.text+0xff2)：对‘deepmd::DeepPotModelDevi::~DeepPotModelDevi()’未定义的引用
c_api.cc:(.text+0x108a)：对‘deepmd::DeepPotModelDevi::~DeepPotModelDevi()’未定义的引用
c_api.o：在函数‘DP_DeepTensor::DP_DeepTensor()’中：
c_api.cc:(.text+0x11c0)：对‘deepmd::DeepTensor::DeepTensor()’未定义的引用
c_api.o：在函数‘DP_NewDeepTensor’中：
c_api.cc:(.text+0x12af)：对‘deepmd::DeepTensor::DeepTensor(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
c_api.cc:(.text+0x1300)：对‘deepmd::DeepTensor::~DeepTensor()’未定义的引用
c_api.cc:(.text+0x1392)：对‘deepmd::DeepTensor::~DeepTensor()’未定义的引用
c_api.o：在函数‘DP_NewDeepTensorWithParam’中：
c_api.cc:(.text+0x154c)：对‘deepmd::DeepTensor::DeepTensor(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用`
What does this mean?

**Comment by robinzyb** [comment]
The `-L `option in `gfortran` command  is used to include the header files, you can include the path of header files using  `-L @TENSORFLOW_LIB_FILE_PATH ` actually, I don't know how you type the command, you can check out the help manual of gfortran, which can tells you in detail, including how to include header files.

**Comment by luowh35** [comment]
the command I type is :
`gfortran -o fortran_call c_api.o deepmd_wrapper.o fortran_call.o -lstdc++ -L $deepmd_root/lib -L $tensorflow_root/lib -Wl,--no-as-needed -ldeepmd_op -ldeepmd -ltensorflow_cc -ltensorflow_framework -Wl,-rpath=$deepmd_root/lib -Wl,-rpath=$tensorflow_root/lib`
and I get this wrong.

**Comment by Cloudac7** [comment]
You could refer to https://github.com/Cloudac7/DeePMD-kit-Fortran-C-interface, which is an adapt version using the C API.

**Comment by luowh35** [comment]
Thank you so much!
